apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: web-app
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # 自动扩缩配置
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
        # 基于内存使用率的自动扩缩
        autoscaling.knative.dev/metric: "memory"  
        autoscaling.knative.dev/target: "70"      # 内存使用率超过70%时扩展
        # 配置冷启动行为
        autoscaling.knative.dev/scale-down-delay: "30s"  # 延迟缩容
    spec:
      containers:
        - image: ${REGISTRY_URL}/web-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: RENDER_TIME
              value: "20"  # 页面渲染时间
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 64Mi 